# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170802_0418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='DatabaseLog',
        ),
    ]
