# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170802_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselog',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
