# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditArticle',
            fields=[
                ('reddit_id', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('reddit_created', models.IntegerField(default=0)),
                ('reddit_title', models.TextField(null=True)),
                ('reddit_flair', models.TextField(null=True)),
                ('reddit_nsfw', models.BooleanField(default=False)),
                ('reddit_score', models.IntegerField(default=0)),
                ('article_url', models.URLField(null=True)),
                ('article_domain', models.URLField(null=True)),
                ('article_title', models.TextField(null=True)),
                ('article_authors', models.TextField(null=True)),
                ('article_text', models.TextField(null=True)),
                ('article_top_image', models.URLField(null=True)),
                ('article_keywords', models.TextField(null=True)),
                ('article_publish_date', models.TextField(null=True)),
                ('time_retrieved', models.IntegerField(default=0)),
            ],
        ),
    ]
