# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewslyApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditarticle',
            name='reddit_rank',
            field=models.IntegerField(default=0),
        ),
    ]
