# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewslyApi', '0002_redditarticle_reddit_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redditarticle',
            options={'ordering': ['-time_retrieved', 'reddit_rank']},
        ),
    ]
