# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewslyApi', '0003_auto_20170729_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditarticle',
            old_name='article_top_image',
            new_name='article_top_image_url',
        ),
    ]
