# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewslyApi', '0004_auto_20170803_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditarticle',
            name='article_top_image',
            field=models.ImageField(null=True, upload_to='articles'),
        ),
    ]
