# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewslyApi', '0005_redditarticle_article_top_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditarticle',
            name='article_top_image',
            field=models.ImageField(null=True, upload_to='article-images'),
        ),
    ]
