# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewslyApi', '0005_auto_20170315_1117'),
        ('NewslyApi', '0006_auto_20170803_0357'),
    ]

    operations = [
    ]
